all: compile link

CC=gcc
CFLAGS=-I src/include -std=c11 -Wall -g -O0
LDFLAGS=-L src/lib/ -lraylib -lopengl32 -lgdi32 -lwinmm

compile:
	$(CC) $(CFLAGS) -c src/*.c 
link:
	$(CC) $(CFLAGS) *.o $(LDFLAGS) -o main.exe
	